routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PelangganController;
use App\Http\Controllers\TransaksiController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

Route::resource('products', ProductController::class);
Route::resource('pelanggan', PelangganController::class);
Route::resource('transaksi', TransaksiController::class);
Route::get('/update_password', [HomeController::class, 'update_password'])->name('update_password');
Route::patch('/store_password', [HomeController::class, 'store_password'])->name('store_password');

Route::middleware(['admin'])->group(function () {
    Route::get('/update_password', [HomeController::class, 'update_password'])->name('update_password');
    Route::patch('/store_password', [HomeController::class, 'store_password'])->name('store_password');
});

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/transaksi', function () {
//     return view('welcome transaksi');
// });


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    use HasFactory;

    protected $fillable = [
        'id_pelanggan', 'id_produk', 'jumlah', 'harga'
    ];
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaksi;
use Illuminate\Http\Request;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transaksi = Transaksi::latest()->paginate(5);
        return view('transaksi.index', compact('transaksi'))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transaksi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id_pelanggan' => 'required',
            'id_produk' => 'required',
            'jumlah' => 'required',
            'harga' => 'required',
        ]);

        Transaksi::create($request->all());

        return redirect()->route('transaksi.index')->with('success', 'Transaksi created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function show(Transaksi $transaksi)
    {
        return view('transaksi.show', compact('transaksi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaksi $transaksi)
    {
        return view('transaksi.edit', compact('transaksi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaksi $transaksi)
    {
        $request->validate([
            'id_pelanggan' => 'required',
            'id_produk' => 'required',
            'jumlah' => 'required',
            'harga' => 'required',
        ]);

        $transaksi->update($request->all());

        return redirect()->route('transaksi.index')->with('success', 'transaksi updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaksi $transaksi)
    {
        $transaksi->delete();

        return redirect()->route('transaksi.index')->with('success', 'transaksi deleted successfully');
    }
}

resources/views/transaksi/create.blade.php
@extends('template.layout')
@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Add New Transaksi</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-primary" href="{{ 
route('products.index') }}"> Back</a>
    </div>
  </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> There were some problems with your
  input.<br><br>
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif

<form action="{{ route('products.store') }}" method="POST">
  @csrf

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Id pelanggan:</strong>
        <input type="text" name="id_pelanggan" class="form-control" placeholder="id_pelanggan">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Id produk:</strong>
        <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail"></textarea>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Jumlah:</strong>
          <textarea class="form-control" style="height:150px" name="jumlah" placeholder="jumlah"></textarea>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <strong>Harga:</strong>
            <textarea class="form-control" style="height:150px" name="harga" placeholder="harga"></textarea>
          </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btnprimary">Submit</button>
        </div>
      </div>

</form>
@endsection

resources/views/transaksi/edit.blade.php
@extends('template.layout')

@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Edit transaksi</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-primary" href="{{route('transaksi.index') }}"> Back</a>
    </div>
  </div>
</div>
@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> There were some problems with your
  input.<br><br>
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif

<form action="{{ route('transaksi.update',$transaksi->id) }}" method="POST">
  @csrf
  @method('PUT')

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Id transaksi:</strong>
        <input type="text" name="id_transaksi" value="{{ $transaksi->id_transaksi }}" class="form-control" placeholder="id_transaksi">
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Id produk:</strong>
        <input type="text" name="id_produk" value="{{ $transaksi->id_produk }}" class="form-control" placeholder="id_produk">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Jumlah:</strong>
        <input type="text" name="jumlah" value="{{ $transaksi->jumlah }}" class="form-control" placeholder="jumlah">
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Harga:</strong>
        <input type="text" name="harga" value="{{ $transaksi->harga }}" class="form-control" placeholder="harga">
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 textcenter">
      <button type="submit" class="btn btnprimary">Submit</button>
    </div>
  </div>
</form>
@endsection

resources/views/transaksi/index.blade.php
@extends('template.layout')
@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Laravel 9 CRUD Example from scratch - ItSolutionStuff.com</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-success" href="{{ route('transaksi.create') }}"> Create New transaksi</a>
    </div>
  </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
  <p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
  <tr>
    <th>No</th>
    <th>Id pelanggan</th>
    <th>Id produk</th>
    <th>Jumlah</th>
    <th>Harga</th>
    <th width="280px">Action</th>
  </tr>
  @foreach ($pelanggan as $product)
  <tr>
    <td>{{ ++$i }}</td>
    <td>{{ $transaksi->id_pelanggan }}</td>
    <td>{{ $transaksi->id_produk }}</td>
    <td>{{ $transaksi->jumlah }}</td>
    <td>{{ $transaksi->harga }}</td>
    <td>
      <form action="{{ route('transaksi.destroy',$transaksi->id) }}" method="POST">

        <a class="btn btn-info" href="{{ 
route('transaksi.show',$transaksi->id) }}">Show</a>

        <a class="btn btn-primary" href="{{route('transaksi.edit',$transaksi->id) }}">Edit</a>

        @csrf
        @method('DELETE')

        <button type="submit" class="btn btn-danger">Delete</button>
      </form>
    </td>
  </tr>
  @endforeach
</table>

{!! $transaksi->links() !!}

@endsection

resources/views/transaksi/show.blade.php
@extends('template.layout')

@section('content')
<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2> Show Transaksi</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-primary" href="{{route('transaksi.index') }}"> Back</a>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Id pelanggan:</strong>
      {{ $transaksi->id_pelanggan }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Id produk:</strong>
      {{ $transaksi->id_produk }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Jumlah:</strong>
      {{ $transaksi->jumlah }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Harga:</strong>
      {{ $transaksi->harga }}
    </div>
  </div>
</div>
@endsection